### ISSUE TITLE
c2ffi dies when used on SDL2_gfxPrimitives.h

### ISSUE THREAD

**Issue by mabragor** [rpav/c2ffi#24] opened 2015-12-16 17:05 UTC
Hi, Ryan!

I'm trying now to generate bindings for SDL2_gfx.
My header file looks like
```c
#include <SDL2/SDL2_gfxPrimitives.h>
```
and the command I use to generate bindings is
```bash
~/quicklisp/local-projects/c2ffi/build/src/c2ffi SDL2_gfx.h -M macros.h -A x86_64-pc-linux-gnu > 1.txt
```
There's a lot of normal JSON output, which does to 1.txt
and then it fails with an assertion

c2ffi: /home/popolit/llvm/tools/clang/lib/AST/RecordLayoutBuilder.cpp:2806: const clang::ASTRecordLayout &clang::ASTContext::getASTRecordLayout(const clang::RecordDecl *) const: Assertion `D && "Cannot get layout of forward declarations!"' failed.
Aborted

Honestly, I've no clue where to go from here and how to diagnose it. Would be happy to hear any suggestions.

Best regards,
Alex

**Comment by rpav** [comment] 2015-12-16 17:11
Confirmed; this is probably c2ffi not checking some relevant flag and is a bug with c2ffi.  Looking into it now.

**Comment by rpav** [comment] 2015-12-16 17:14
...oddly it seems to be happening in the middle of stdio.h or similar, which seems odd since it's included by everything ever.  Perhaps this assert is newer in clang (though usually I don't compile with asserts, since it doesn't play nice with CL).

**Comment by mabragor** [comment] 2015-12-16 17:24
How can I compile clang without asserts then?

2015-12-16 18:16 GMT+01:00 Ryan Pavlik <notifications@github.com>:

**Comment by rpav** [comment] 2015-12-16 17:25
Ah, it looks like this is a problem after having added bit-size and bit-alignment for simple types.  Apparently, forward-declared structs are considered simple types, and thus (used to) get blank declarations in the JSON.  I'm not sure whether having them included is "good" or not, but I'm also not sure if autowrap or anything else depends on them, so I'll leave them in for the moment.

**Comment by rpav** [comment] 2015-12-16 17:26
It's one of the cmake flags; I suggest cmake-gui or similar for going through and finding it if you want it.  However, even without this may still crash.  Once I fix this issue, it should be fine asserts or otherwise.

**Comment by mabragor** [comment] 2015-12-16 17:27
Oh, found it on LLVM page -- will see if it will work.

2015-12-16 18:24 GMT+01:00 Alexandr Popolitov <popolit@gmail.com>:

**Comment by rpav** [comment] 2015-12-16 18:52
This should be fixed.

**Closed** 2015-12-30 18:29 UTC
